.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/commit-message-linter.yml
.github/workflows/release-sub-projects.yml
.github/workflows/release-unstable.yml
.github/workflows/release.yml

feat: add release action and templates

---

.github/workflows/release-sub-projects.yml
.github/workflows/release.yml

feat(ci): update release action

---

docker-compose.yaml

- Bumped images version to v1.0.0
None.

Release v1.1.0

---

docker-compose.yaml

ci: bump images version

---

README.md

chore: remove discord badge

---

kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

Update portals and api images version to v1.1.0 in k8s files
None.

fix: update portals and api images version to v1.1.0 in k8s files

---

docker-compose-stage.yaml
docker-compose.yaml

change redis version to redis:6

feat(improve): fixed redis version

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.0.0
None.

Release v1.2.0

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

Reverts UniBee-Billing/unibee#13

chore: revert "Release v1.2.0"

---

README.md
docker-compose-stage.yaml
docker-compose.yaml
kubernetes/unibee_nginx.yaml
nginx.conf

docker compose add license support

feat(license): docker compose add license support

---

docker-compose.yaml
nginx.conf

Upgrade nginx to 1.27.2 and fix typo
None.

chore: upgrade nginx to 1.27.2 and fix typo

---

.github/workflows/release-sub-projects.yml

Update k8s image version when dispatch release action
None.

feat: update k8s image version when dispatch release action

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.3.0
None.

Release v1.3.0

---

.github/workflows/release-sub-projects.yml

Use env variable instead of hardcode version
None.

fix: use env variable instead of hardcode version

---

.github/workflows/release-sub-projects.yml
docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.3.1
None.

Release v1.3.1

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml

Bump admin portal to v1.3.2
None.

fix: bump admin portal to v1.3.2

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.4.0
None.

Release v1.4.0

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

ci: version bump to v1.4.1

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.4.2
None.

Release v1.4.2

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml

ci: release admin portal v1.5.1

---

docker-compose.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.5.1
None.

Release v1.5.1

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.5.2
None.

Release v1.5.2

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.6.1
None.

Release v1.6.1

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.6.2
None.

Release v1.6.2

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.6.3
None.

Release v1.6.3

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.7.1
None.

Release v1.7.1

---

docker-compose.yaml
kubernetes/unibee_admin_portal.yaml
kubernetes/unibee_api.yaml
kubernetes/unibee_user_portal.yaml

- Bumped images version to v1.7.2
None.

Release v1.7.2
